version: "3"

services:
  mermaid:
    build: .
    image: "public.ecr.aws/citizensadvice/mermaid${MERMAID_VERSION_TAG}"
    volumes:
      - ./:/mermaid
      - node_modules:/mermaid/node_modules

volumes:
  node_modules: {}
